config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :new, :create, :show] do
    resources :comments, only: [:create]
  end

  resource :session, only: [:new, :create, :destroy]

  resources :goals do
    resources :comments, only: [:create]
  end

  resources :comment

  root to: "users#index"

  post "cheer/:goal_id" => "goals#cheer", as: :cheer

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true

  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id,
    inverse_of: :authored_comments
  )
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :body, :setting, :user, presence: true

  belongs_to(
    :user,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id,
    inverse_of: :goals
  )

  include Commentable

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token
  after_initialize :add_cheers

  attr_reader :password

  has_many(
    :goals,
    class_name: "Goal",
    foreign_key: :user_id,
    primary_key: :id,
    inverse_of: :user
  )

  has_many(
    :authored_comments,
    class_name: "Comment",
    foreign_key: :user_id,
    primary_key: :id,
    inverse_of: :author
  )

  include Commentable

  def self.find_by_credentials(username, password)
    @user = User.find_by_username(username)
    return nil if @user.nil?

    return @user if @user.is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token
    self.session_token = generate_session_token
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def add_cheers(num = 10)
    self.cheers = num
    self.save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?, :is_page_owner?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def log_in_user(user)
    session[:session_token] = user.reset_session_token
  end

  def log_out_user
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def require_logged_in?
    redirect_to new_session_url unless signed_in?
  end

  def is_page_owner?(user)
    current_user == user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    if params[:user_id]
      user = User.find(params[:user_id])
      @comment = user.comments.new(comment_params)
    elsif params[:goal_id]
      goal = Goal.find(params[:goal_id])
      @comment = goal.comments.new(comment_params)
    end

    @comment.author_id = current_user.id

    if @comment.save
      if params[:user_id]
        redirect_to user_url(user)
      elsif params[:goal_id]
        redirect_to user_url(goal.user)
      end
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to :back
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @parent = @comment.commentable
    @comment.destroy

    if @parent.class == User
      redirect_to user_url(@parent)
    elsif @parent.class == Goal
      redirect_to user_url(@parent.user)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable, dependent: :destroy
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
    @goal = Goal.new
    render :new
  end

  def create
    @goal = current_user.goals.new(goal_params)
    if @goal.save
      redirect_to user_url(current_user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
    render :edit
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to user_url(current_user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def cheer
    @goal = Goal.find(params[:goal_id])
    @goal.cheers += 1
    user = User.find(current_user.id)
    user.cheers -= 1
    @goal.save
    user.save
    redirect_to :back
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to user_url(current_user)
  end

  def goal_params
    params.require(:goal).permit(:body, :setting)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(user_params[:username], user_params[:password])

    if @user
      log_in_user(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Incorrect username and/or password"]
      render :new
    end
  end

  def destroy
    log_out_user
    redirect_to new_session_url
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    <<-HTML.html_safe
    <input type="hidden"
    name="authenticity_token"
    value="#{form_authenticity_token}">
    HTML
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<form action="<%= goal_url(@goal) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>

  <label>
    Goal
    <input type="text" name="goal[body]" value="<%= @goal.body %>">
  </label>


  Privacy Setting
  <label>
    <input type="radio" name="goal[setting]" value="Public"
    checked if <% @goal.setting == "Public" %>>
    Public
  </label>

  <label>
    <input type="radio" name="goal[setting]" value="Private"
    checked if <% @goal.setting == "Private" %>>
    Private
  </label>

  <button>Update Goal</button>

</form>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<form action="<%= goals_url %>" method="post">
  <%= auth_token %>

  <label>
    Goal
    <input type="text" name="goal[body]" value="<%= @goal.body %>">
  </label>
  <br><br>

  Privacy Setting
  <br>
  <label>
    <input type="radio" name="goal[setting]" value="Public"
    checked if <% @goal.setting == "Public" %>>
    Public
  </label>

  <label>
    <input type="radio" name="goal[setting]" value="Private"
    checked if <% @goal.setting == "Private" %>>
    Private
  </label>
  <br>

  <button>Create Goal</button>

</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalSetter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if signed_in? %>
  Welcome <%= current_user.username %> | ★ <%= current_user.cheers %> |
  (Not <%= current_user.username %>? <%= link_to "Sign Out", session_url, method: :delete %>)
<% else %>
  <%= link_to "Sign In", new_session_url %>
  <%= link_to "Sign Up", new_user_url %>
<% end %>

<hr>
<ul>
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
<% end %>
</ul>

<%= yield %>

<hr>
<a href="<%= users_url %>">Home</a>
<br>
<% if signed_in? %>
  <a href="<%= user_url(current_user) %>">My Profile</a>
<% end %>

</body>
</html>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
  <a href="<%= user_url(user) %>"><%= user.username %></a>
  <br>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<form action="<%=users_url%>" method="post">
  <%= auth_token %>

  <label>
  Username
    <input type="text" name="user[username]">
  </label>
  <br>

  <label>
  Password
    <input type="password" name="user[password]">
  </label>
  <br>

  <button>Sign Up</button>

</form>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Goals</h1>

<h3>User Comments:</h3>
<ul>
<% @user.comments.each do |comment| %>
  <li><%= comment.body %> | By <a href="<%= user_url(comment.author) %>"><%= comment.author.username %></a> <%= time_ago_in_words(comment.created_at) %> ago</li>
<% end %>
</ul>

<% if signed_in? && !is_page_owner?(@user) %>
  <form action="<%= user_comments_url(@user) %>" method="POST">
    <%= auth_token %>
    <input type="text" name="comment[body]" id="user_comment">
    <input type="submit" value="Add User Comment" id="add_user_comment">
  </form>
<% end %>


<h3>Goals:</h3>
<ol>
<% @user.goals.each do |goal| %>
  <% if goal.setting == "Public" || is_page_owner?(@user) %>
    <strong><li><%= goal.body %> ★ <%= goal.cheers %></li></strong>
    <ul>
    <%= link_to "Cheer!", cheer_url(goal), method: :post%>
    <% goal.comments.each do |comment| %>
      <li><%= comment.body %> | By <a href="<%= user_url(comment.author) %>"><%= comment.author.username %></a> <%= time_ago_in_words(comment.created_at) %> ago</li>
    <% end %>
    </ul>

    <% if is_page_owner?(@user) %>
      <%= button_to "Edit Goal", edit_goal_url(goal), method: :get %>
      <%= button_to "Delete Goal", goal_url(goal), method: :delete %>
      <br>
    <% end %>

    <% if signed_in? && !is_page_owner?(@user) %>
      <form action="<%= goal_comments_url(goal) %>" method="POST">
        <%= auth_token %>
        <input type="text" name="comment[body]" id= "comment_<%= goal.body %>">
        <input type="submit" value="Add Goal Comment" id="<%= goal.body %>">
      </form>
    <% end %>
  <% end %>
<% end  %>
</ol>
<br>

<% if is_page_owner?(@user) %>
  <a href="<%= new_goal_url %>"> New Goal</a>
<% end %>